### PR TITLE
Added a few showcase frames

### PR DESCRIPTION
**Pull request by G-e-n-e-v-e-n-s-i-S**
Showcases:
 - Assassin's Creed Memory Corridor
 - Bloomburrow Borderless Anime
 - Bloomburrow Woodland
 - Doctor Who TARDIS
 - Dominaria Stained Glass
 - Eldraine Enchanting Tales
 - Fallout Pip-Boy
 - Gatewatch Baseball
 - Ikoria Crystal
 - Innistrad Double Feature †
 - Innistrad Double Feature Walker †
 - Innistrad Equinox (only single faced)
 - Ixalan Aztec
 - Ixalan Caverns Aztec
 - Ixalan Legends
 - Lord of the Rings - Ring
 - Lord of the Rings - Scroll
 - Lord of the Rings - Scroll Saga
 - New Capenna Art Deco †
 - New Capenna Art Deco Walker †
 - New Capenna Golden Age †
 - New Capenna Skyscraper †
 - Ravnica Citadel
 - Ravnica Dossier
 - Tarkir Dragon
 - Thunder Junction Breaking News (crown from card conjurer)
 - Thunder Junction Vault
 - Thunder Junction Wanted
 - Unfinity Galaxy

Misc:
 - Punch-out Counter Sheet
 - Kamigawa Full Art Basics
 - Lord of the Rings - Mechanics Reminder
 - Unfinity Attraction †

†  based on blanks from Card Conjurer, downscaled and tweaked by myself

### CODE REVIEW

**Comment by CajunAvenger** [comment]
k i don't get why so many of these have an option to fullsize the art that isn't actually useful for anything

**Comment by CajunAvenger** [comment]
Additional todos, i've got most the images and some of the frames partially built but just to have them posted

- Constellation Theros Showcase
- Spellbook M21 Showcase
- Ninjas Kamigawa Showcase
- Samurai Kamigawa Showcase
- Neon Kamigawa Showcase
- Kamigawa Basics
- Fangs Innistrad Showcase
- updates for Amonkhet Invocation
- Compleated Planeswalkers

**Comment by CajunAvenger** [comment]
Looking at TARDIS frame

- idk why rules text cap is here, that's pretty redundant with chops on non-level frames
- idk what card colored border is doing here at all, its not on the canon cards and its just adding a random gray tint no matter the color
- we should prob just make the antialiased corners the default border_mask corners instead of this thing. can leave the squared corners

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
> i don't get why so many of these have an option to fullsize the art that isn't actually useful for anything

that helps make popout art?

> we should prob just make the antialiased corners the default border_mask corners

being able to toggle corners on or off is very useful

> rarity coordinates should probably be offsets instead

they really should

**Comment by CajunAvenger** [comment]
having square corners is useful, is having the pixely rounded corners useful when you've made good smooth corners?

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
That's useful when you want to make the corners transparent in GIMP after exporting. You can make it work from anti-aliased or square corners, but this offers a simpler alternative for less tech-savvy people.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
This is becoming unwieldy. Would you like me to move each template into an individual pull request so it's less of a pain to review?

**Comment by CajunAvenger** [comment]
hrm. i think being able to access them all at once for easier bulk edits is still better. just need to find like two days to actually go through it all qq

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
No worries, take your time, nothing urgent.

**Comment by CajunAvenger** [comment]
working my way down tardis rn, will probably be the longest of the bunch

questions
* not sure we need both font cap and chops?
* i don't get why the border tint option a) is here, b) is on by default, c) says it tints per the card's color but only tints rgb(0, 21, 34)?

updates so far
* changed to custom font system adventure overhaul solidified
* cut alt rarity scripts as they've been offloaded to magic.mse-game
* have done the same for mainframe rarity now
* also clamp that's a useful one to have globally
* changed style-level flavor bar to the set-level one that already exists
* changed to card_number_script_core

todo
* going to finish off the set/card-level stamp system and supplement the styling-level one. card overrules styling overrules set
* take a stab at the hd scaling thing and see if that's worth continuing across the others

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
>     not sure we need both font cap and chops?

isn't font cap incidentally part of the new font system? if so can definitely delete it.

>     * i don't get why the border tint option a) is here, b) is on by default, c) says it tints per the card's color but only tints rgb(0, 21, 34)?

yeah.

>     * cut alt rarity scripts as they've been offloaded to magic.mse-game
>     * also clamp that's a useful one to have globally
>     * going to finish off the set/card-level stamp system and supplement the styling-level one. card overrules styling overrules set

it occurs to me that I have already done a lot of this work here -> #21
that PR is itself slowly becoming a behemoth, but addressing it first would allow me to simplify the showcase frames greatly, making it easier to review them. for example, I have already written code that will take care of the set code/illustrator/copyright in a way that adapts to the template width and height.

**Comment by CajunAvenger** [comment]
guess i can pivot to that instead

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
It is a ton of changes to sensitive files so I understand if you want to leave it for later, cause it's definitely gonna take more than a week-end

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
going to take a day or two to convert these to modules

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
I'd like to take tomorrow to put some final polish before you review

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
Alright, life is happening so I can't give this all the attention I'd like, so I'm just gonna let you go ahead and review it cause I don't want to delay this too long.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
Currently, in the `styling.rarity_offsets` field, if the user tries to increase the width alors, it doesn't increase the width of the symbol, it just shifts it to the right. (It increases the width of the field but the user doesn't care about that.)

Similarly, if the user tries to increase the height alone, it doesn't do anything.

If the user increases the width and height at the same time, it works. So maybe change that field to just have "left,top,size" instead of "left,top,width,height"?

**Comment by CajunAvenger** [comment]
mkay, think i'm ready when you are

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
okay, I think I'm good for now

**Comment by CajunAvenger** [comment]
* Updated to MSE 2.5.2
* Added Assassin's Creed Memory Corridor
* Added Bloomburrow Borderless Anime
* Added Bloomburrow Woodland
* Added Compleated Planeswalkers
* Added Duskmourn Paranormal
* Added Kamigawa Neon
* Added Kamigawa Ninja
* Added Kamigawa Samurai
* Added Innistrad Fang
* Added Theros Constellation
* Added Capenna Art Deco
* Added Capenna Golden Age
* Added Capenna Skyscraper
* Added Doctor Who TARDIS
* Added Dominaria Stained Glass
* Added Eldraine Enchanting Tales
* Added Fallout PipBoy
* Added Ikoria Crystal
* Added Innistrad Double Feature
* Added Innistrad Equinox
* Added Ixalan Treasures
* Added Ixalan Legends
* Added Ixalan Caverns
* Added Lord of the Rings Ring
* Added Lord of the Rings Scroll
* Added Ravnica City Mural
* Added Ravnica Dossier
* Added Tarkir Dragon Wing
* Added Thunder Junction Breaking News
* Added Thunder Junction Vault
* Added Thunder Junction Wanted Poster
* Added Unfinity Of Tomorrow
* Added Unfinity Attractions
* Added Secret Lair Baseball
* Added revamped option to Amonkhet Invocations
* Added UB stamp compatibility to old showcase frames
* Added foils and popouts modules
* Add foil_mask blending system
* Fixes #57

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
This also contained
- Punch-out Counter Sheet
- Kamigawa Full Art Basics
- Lord of the Rings - Mechanics Reminder

**Pull request merged**
