### PR TITLE
[274/274] magic-modules rollout

### PR DESCRIPTION
**Pull request by CajunAvenger**
Adding the most critical modules to as many frames as we can.

Information:
add to all M15 frames, consider making the 8th and Old versions of this module and applying them as well

Stamps:
add to all M15 frames, add Triangle backing stamp where reasonable. consider adding the color stamp backings to the module. 

Corners:
add to all frames

Card Symbol:
replace where it already exists

Popout arts and Overlays:
will need changed to 1000 level z index

Rarity:
change to include file
add alt rarity
add card rarity

Indicators:
Change image sources and change dependency to magic-modules

Watermarks:
Change image to watermarks_scripts
add watermark_include := "/magic-modules.mse-include", this will be mass removed in the future once we can safely change blends to use magic-modules and let us remove the magic-watermarks dependency now instead of trying to mass remove the more complicated line

also:
consider transformation: this would like to have a patcher to convert old extra-card-field corners into transformation

progress
AGClassic: 4/4
Classicshifted: 6/6
FPM: 6/6
Future: 12/12
Genevensis: 10/10
New: 62/62
Old: 19/19
Planeshifted: 7/7
Other: 59/59
M15 Frames: 88/89
* Mainframe DFC

Total: 273/274

### CODE REVIEW

**Comment by CajunAvenger** [comment]
module updates so far:

blends;
* indicator blending uses /magic-modules.mse-include. this will need to be a dependency for anything using m15 indicators
* added parameter `blend_type` to color_combination, allowing an image to use the blend files for another image type (for example, type stamp and type ubstamp can have different template() returns but use one set of x_blend_type files since they're identical)
* added module_card, module_identity, module_stamp, module_ubstamp, module_nyx, module_snow, and module_alias, which blend from the files in magic-modules. the links in template_prefix/_suffix map will still need to be provided (for picking the folder with the right resolution and such)
* also added module_ptbox, which takes an optional `vehicle: boolean` parameter for if the ptbox should be vehicle instead.
* added `watermark_include := "/magic-watermarks.mse-include"`, templates will overwrite this with `watermark_include := "/magic-modules.mse-include/watermark"` until we can safely remove magic-watermarks, at which point the template definitions will be mass removed and the blend definition changed to magic-modules

magic-modules
* added `cards/375 m15 simple/` for the standard 375x523 Magic card. `cards/375 m15 cut` is reserved for the spree handling update in 1.4
* added `crowns/375/`, with further directories of `borderless/`, `companion/`, and `nyx/`
* added preliminary ini_script, card_fields, and styling_fields for crowns. this will want to be expanded and get _dfc/_tfc files before merging
* added `extras/`, currently holding the evobar and `aliases/`
* added `pts/375 m15/`, holding space for `pts/750 m15` and `pts/375 new`
* added `stamps/backs/` with a basic backing stamp for round and triangle stamp, `375 round/` for the color stamp backs, `375/round/shifted/` for the planeshifted ones, `375 ub/` for triangle backs, `375 ub/shifted/` for planeshifted ones, `750 round outlined/` for the Planeswalker stamps, and tempfile `hires ub/` for the hires universes beyond stamps which are made for like a 1500x2100 template.
* added `trims/`, holding `nyx/`, `snow/`, `vehicle.png`, and 375x523 masks for them
* added styling level `mainframe_rarity_name` to rarity/styling_fields, allowing more rarity symbols per set file.

script
* added `information_secondary_shift_with_pt_X`, to disable the realignment of secondary copyright for frames like Aftermath and Flip where the PT doesn't affect its placement.
* added cull_directions so direction blending doesn't mess up the has_identity checks

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
what's the reasoning behind the need for the apply custom fonts styling field?

**Comment by CajunAvenger** [comment]
> I'll do my custom frames.
> 
> What's the reasoning behind the need for the `apply custom fonts` styling field? Prevent error messages while the user is typing?

yes. can also disable/enable while testing without having to delete out 4 boxes

**Comment by CajunAvenger** [comment]
after working with the separator module some, think it makes more sense to have this be a dedicated flavor bar and have the class bar be a separate thing

**Comment by CajunAvenger** [comment]
loyalty ability tweaking:

* reverted 190 margin to 130
* added "automatic" option to styling.number_of_textboxes
* divided `card_fields` into `ability_fields` (that has loyalty boxes and colons), `separator_fields` (that has the in-between separators), and `stripes_fields` (that has the main stripe blocks). These are all included in `card_fields` but can be included separately now (for frames like Outlaw Planeswalkers that need ability and stripe but not the backdrop)
* divided `styling_fields` into `styling_formatting` that has number_of_textboxes, move_separators, and move_loyalty_costs, and `styling_recoloring` that has the recoloring options. again both called in `styling_field`

**Comment by CajunAvenger** [comment]
roundup of updates for review
FRONTEND
* Added Auto nyx Set option. Mainframe frames will use this to determine if Nyx frame should be applied to base Enchantments.
* Added Alternate nyx Set option which replaces the texture used by Nyx. This accepts a color-filling file name in magic-mainframe-extras (`examples/border/nyx.png`), or specific prebuilts (`star`).
* Alias as Cardname Set option has been replaced with CARDNAME replacement. This changes if CARDNAME uses the card's name, the card's alias, or the card's main type.
* M15 Sagas now supports Cases and customizeable Class bars
* Mainframe DFC now supports Cases and 6 ability planeswalkers
* Mainframe DFC's Saga and Clear frames now have a dedicated transform node section.
* M15 Mainframe now has Miracle support for Legendary, Inverted, FNM, and Conspiracy frames.
* Updated localizations through Duskmourn, except for Japanese Duskmourn keywords.

BACKEND
* color_background now accepts the optional parameters `folder`, which is appended to the beginning of the file name for blend masks, and `blend_type` which substitutes the type used in the file name. This allows for blend masks to be moved to new folders and shared for images that use identical ones.
* added module_card, module_identity, module_stamp, module_ubstamp, module_identity, module_snow, module_alias, and module_nyx, which card_background etc replacements that use folder:template_prefix[type] already
* module_nyx is more complicated, accessing the new Alternate Nyx set option to minimize how much templates need to copy to get it
* module_ptbox also exists, accepting `vehicle: boolean` for if template_prefix["pt"]/vpt.png should be used instead.
• added the card frames shared among mainframe templates to cards module
* added the crowns module
* added the extras module, holding alias and evobar
* added the levels module, holding leveler arrows and textbox textures
* added the trims modules, holding draft, miracle, nyx, snow, and their trim masks. Additionally holds "star", specially supported via Alternate Nyx, which may be expanded in future.
* added stamp backs for Mainframe to the stamps module

**Comment by CajunAvenger** [comment]
from crush:
* mainframe tokens doesn't have stamps
* unindent nonloyalty abilities needs to be initialized
* draft matters isn't working on the front face of dfc and doesn't fill the bottom of sagas
* transform defaults are weird
* tinker with modal dfc node overrulling the style option
* miracle should be added to the checklist
* the season flag and lesson symbol go under conspiracy scrolls
* the season flag is visible in the lesson symbol hole

**Comment by CajunAvenger** [comment]
from crush:
* mainframe tokens doesn't have stamps
* unindent nonloyalty abilities needs to be initialized
* draft matters isn't working on the front face of dfc and doesn't fill the bottom of sagas
* transform defaults are weird
* tinker with modal dfc node overrulling the style option
* miracle should be added to the checklist
* the season flag and lesson symbol go under conspiracy scrolls
* the season flag is visible in the lesson symbol hole

**Comment by CajunAvenger** [comment]
file editor now live: https://mse-editor.neocities.org/

**Pull request merged**
